version: '3.4'

services:
  workorder.api:
    image: ${DOCKER_REGISTRY-}workorderapi
    build:
      context: .
      dockerfile: WorkOrder.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata:
    driver: local